#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh &

bspc monitor -d TERM WEB CODE SRV NOTE CHAT MAIL TLS 
# ZEN

~/.scripts/bspwm-toggle-gap

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
# bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
# bspc config honor_size_hints true 



bspc config focus_follows_pointer true

#Settings for manual splitting
bspc config split_ratio         0.50



bspc config border_width 2
bspc config normal_border_color "#282c34"
bspc config active_border_color "#5c6370"
bspc config focused_border_color "#5c6370"


# bspc desktop CODE --layout monocle

# Use command: xprop | grep WM_CLASS

bspc rule -a kitty desktop="TERM" follow=on
bspc rule -a firefox desktop="WEB" follow=on
bspc rule -a Code desktop="CODE" follow=on
bspc rule -a marktext desktop="NOTE" follow=on
bspc rule -a beekeeper-studio desktop="SRV" follow=on
bspc rule -a WebApp-WhatsApp4749 desktop="CHAT" follow=on state=pseudo_tiled center=true
bspc rule -a TelegramDesktop desktop="CHAT" follow=on state=pseudo_tiled center=true
bspc rule -a Mailspring desktop="MAIL" follow=on

# bspc rule -a Thunar state=pseudo_tiled

bspc rule -a feh state=floating center=true
bspc rule -a KeePassXC state=floating center=true sticky=on
bspc rule -a ksnip state=floating center=true
bspc rule -a Colorgrab state=floating center=true

# bspc rule -a kitty desktop='^1' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
