#!/bin/bash

gap=15
PANEL_HEIGHT=30

if [ $(bspc config top_padding) = 0 ]; then
    bspc config window_gap $gap
    bspc config top_padding $(($PANEL_HEIGHT-$gap))
    bspc config left_padding -$gap
    bspc config right_padding -$gap
    bspc config bottom_padding -$gap
else
    bspc config window_gap 0
    bspc config top_padding 0
    bspc config top_padding 0
    bspc config left_padding 0
    bspc config right_padding 0
    bspc config bottom_padding 0
fi