#!/bin/bash

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc{,.common} |
    column -t -s $'\t' |
    rofi -no-fixed-num-lines -dmenu -i -markup-rows -no-show-icons -l 15 -yoffset -300 -theme-str 'window {width: 1000;}'
